baseURL = 'https://rsouza01.github.io/BIZZ/'

languageCode = 'en-us'
title = 'Bizz Viewer'
theme = 'gallery'

customJs = ["js/custom.js"]

[module]
  # Preserve the default content directory
  [[module.mounts]]
    source = "content"
    target = "content"
  
  # Mount your external data folder
  [[module.mounts]]
    source = "../data"
    target = "content/magazines"

    